redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

## Globally shared configuration
global:
  # -- Default domain used by all components
  ## Used for ingresses, certificates, SSO, notifications, etc.
  domain: localhost:8080

configs:
  # General Argo CD configuration
  ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  cm:
   dex.config: |
     connectors:
       - type: github
         id: github
         name: GitHub
         config:
           clientID: Ov23liTG5bP9FJWLvOLh # GitHub OAuth App client ID
           clientSecret: $github-dex-secret:dex.github.clientSecret # Alternatively $<some_K8S_secret>:dex.github.clientSecret
           orgs:
           - name: iachub
